server:
  error:
    include-stacktrace: on-param

spring:
  datasource:
    url: jdbc:mysql//localhost:3307/anime?useSSL=false&createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update